[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[background]
path = "/usr/share/backgrounds/greeter.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
theme_name = "Arc-Dark"
# theme_name = "hyprtheme"
# theme_name = "Materia"
# theme_name = "Vimix-dark-compact-doder"
icon_theme_name = "Papirus-Dark"
cursor_theme_name = "Adwaita"
font_name = "ProFont IIx Nerd Font Mono"

[appearance]
# The message that initially displays on startup
greeting_msg = "Welcome!"


[widget.clock]
# strftime format argument
# See https://docs.rs/jiff/0.1.14/jiff/fmt/strtime/index.html#conversion-specifications
format = "%a %b %d  %H:%M:%S"

# How often to update the text
resolution = "500ms"

# Ask GTK to make the label at least this wide. This helps keeps the parent element layout and width consistent.
# Experiment with different widths, the interpretation of this value is entirely up to GTK.
label_width = 150

